/*
 Riley Denoon
Magic Methods 
Modified April 9th 2020
 */

/**
 *
 * @author melanie
 */
public class MagicMethods extends javax.swing.JFrame {

    /**
     * Creates new form MagicMethods
     */
    public MagicMethods() {
        initComponents();
   //declare all variables and they tupes of variables they are below.      
    int numOne;
    int numTwo;
    int numThree;
    int numFour;
    int numFive;
    int numSix;
    int numSeven;
    int numEight;
    int numNine;
    int numTen;
    int numEleven;
    
    int biggest;
    int smallest;
    double power;
    double hypotenuse;
    double rounded;
    double squared;
    double radians;
    
    //set the variables to the the value in the text fields as integers. 
    //numOne = Integer.parseInt(txtNumOne.getText());
    //numTwo = Integer.parseInt(txtNumTwo.getText());
    //numThree = Integer.parseInt(txtNumThree.getText());
    //numFour = Integer.parseInt(txtNumFour.getText());
    //numFive = Integer.parseInt(txtNumFive.getText());
    //numSix = Integer.parseInt(txtNumSix.getText());
    //numSeven = Integer.parseInt(txtNumSeven.getText());
    //numEight = Integer.parseInt(txtNumEight.getText());
    //numNine = Integer.parseInt(txtNumNine.getText());
    //numTen = Integer.parseInt(txtNumTen.getText());
    //numEleven = Integer.parseInt(txtNumEleven.getText());
    
    //set the variables to the value that the method calculates.
    //biggest = Math.max(numOne, numTwo);
    //smallest = Math.min(numThree, numFour);
    //power = Math.pow(numFive, numSix);
    //hypotenuse = Math.hypot(numSeven, numEight);
    //rounded = Math.ceil(numNine);
    //squared = Math.sqrt(numTen);
    //radians = Math.toRadians(numEleven);
    
    //set the labels (answers) by changing the double answers to string then displaying
    //the result of the method's calculations, that were set to variables (ie. biggest).
  
    //lblNumBiggest.setText(Double.toString(biggest));
    //lblNumSmallest.setText(Double.toString(smallest));
    //lblNumPower.setText(Double.toString(power));
    //lblNumHypotenuse.setText(Double.toString(hypotenuse));
    //lblNumRounded.setText(Double.toString(rounded));
    //lblNumRadians.setText(Double.toString(radians));
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNumBiggest = new javax.swing.JLabel();
        txtNumTwo = new javax.swing.JTextField();
        btnBiggest = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNumThree = new javax.swing.JTextField();
        txtNumFour = new javax.swing.JTextField();
        lblNumSmallest = new javax.swing.JLabel();
        btnSmallest = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNumFive = new javax.swing.JTextField();
        txtNumSix = new javax.swing.JTextField();
        lblNumPower = new javax.swing.JLabel();
        btnPower = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNumSeven = new javax.swing.JTextField();
        txtNumEight = new javax.swing.JTextField();
        lblNumHypotenuse = new javax.swing.JLabel();
        btnHypotenuse = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblNumRounded = new javax.swing.JLabel();
        btnRoundUp = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNumTen = new javax.swing.JTextField();
        lblNumSquared = new javax.swing.JLabel();
        btnSquareRoot = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtNumEleven = new javax.swing.JTextField();
        lblNumRadians = new javax.swing.JLabel();
        btnRadians = new javax.swing.JButton();
        txtNumNine = new javax.swing.JTextField();
        txtNumOne = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("     Magic Math Methods");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel2.setText("Enter two numbers and click the button. The program will display the biggest of the two numbers.");

        lblNumBiggest.setText("jlabel");

        txtNumTwo.setText("jTextField2");

        btnBiggest.setText("Biggest");
        btnBiggest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBiggestActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel3.setText("Enter two numbers and click the button. The program will display the smallest of the two numbers.");

        txtNumThree.setText("jTextField1");

        txtNumFour.setText("jTextField1");

        lblNumSmallest.setText("jLabel4");

        btnSmallest.setText("Smallest");
        btnSmallest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmallestActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel4.setText("Enter two numbers and click the button. The program will display the first number to the power of the second.");

        txtNumFive.setText("jTextField1");

        txtNumSix.setText("jTextField2");

        lblNumPower.setText("jLabel5");

        btnPower.setText("Power Result");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel5.setText("Enter the legth of two sides of a right triangle. The program will display the hypotenuse of the triange");

        txtNumSeven.setText("jTextField1");

        txtNumEight.setText("jTextField1");

        lblNumHypotenuse.setText("jLabel6");

        btnHypotenuse.setText("Hypotenuse");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel7.setText("Enter a decimal value. The program will display the value runded up to the nearest integer value. ");

        lblNumRounded.setText("jLabel6");

        btnRoundUp.setText("Round Up");
        btnRoundUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoundUpActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel6.setText("Enter an integer. The program will display the square root of the integer. ");

        txtNumTen.setText("jTextField1");

        lblNumSquared.setText("jLabel8");

        btnSquareRoot.setText("Square Root");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel8.setText("Enter an angle in degrees. The program will display the angle in radians. ");

        txtNumEleven.setText("jTextField1");

        lblNumRadians.setText("jLabel9");

        btnRadians.setText("Radians");

        txtNumNine.setText("jTextField1");

        txtNumOne.setText("jTextField1");
        txtNumOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumOneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumSeven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumEight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lblNumHypotenuse)
                                .addGap(52, 52, 52)
                                .addComponent(btnHypotenuse))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132)
                                .addComponent(lblNumSquared)
                                .addGap(69, 69, 69)
                                .addComponent(btnSquareRoot))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumEleven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134)
                                .addComponent(lblNumRadians)
                                .addGap(77, 77, 77)
                                .addComponent(btnRadians))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumNine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134)
                                .addComponent(lblNumRounded)
                                .addGap(66, 66, 66)
                                .addComponent(btnRoundUp))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(178, 178, 178)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtNumThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtNumFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(lblNumSmallest)
                            .addGap(44, 44, 44)
                            .addComponent(btnSmallest))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtNumFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNumSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(lblNumPower)
                                    .addGap(47, 47, 47)
                                    .addComponent(btnPower)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtNumOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtNumTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(lblNumBiggest)
                            .addGap(50, 50, 50)
                            .addComponent(btnBiggest))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumBiggest)
                    .addComponent(txtNumTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBiggest)
                    .addComponent(txtNumOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumSmallest)
                    .addComponent(btnSmallest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumPower)
                    .addComponent(btnPower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumSeven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumEight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumHypotenuse)
                    .addComponent(btnHypotenuse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumRounded)
                    .addComponent(btnRoundUp)
                    .addComponent(txtNumNine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNumSquared)
                        .addComponent(btnSquareRoot)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumEleven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumRadians)
                    .addComponent(btnRadians)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void btnBiggestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiggestActionPerformed
        
//set the variables to the value in the text fields as integers.
        int numOne = Integer.parseInt(txtNumOne.getText());
    int numTwo = Integer.parseInt(txtNumTwo.getText());
    
    //set the variables to the value that the method calculates.
    int biggest = Math.max(numOne, numTwo);
    
     //set the labels (answers) by changing the double answers to string then displaying
    //the result of the method's calculations, that were set to variables (ie. biggest).
    lblNumBiggest.setText(Integer.toString(biggest));
    
    
    }//GEN-LAST:event_btnBiggestActionPerformed

    private void btnSmallestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmallestActionPerformed
       
//set the variables to the value in the text fields as integers. 
        int numThree = Integer.parseInt(txtNumThree.getText());
        int numFour = Integer.parseInt(txtNumFour.getText());
    
//set the variables to the value that the method calculates
         int smallest = Math.min(numThree, numFour);
    
//set the labels (answers) by changing the double answers to string then displaying
 //the result of the method's calculations, that were set to variables.
    lblNumSmallest.setText(Integer.toString(smallest));
    }//GEN-LAST:event_btnSmallestActionPerformed
    
    private void btnPowerActionPreformed(java.awt.event.ActionEvent evt){
        //set the variables to the value in the text fields as integers.
       int numFive = Integer.parseInt(txtNumFive.getText());
       int numSix = Integer.parseInt(txtNumSix.getText());
    
    //set the variables to the value that the method calculates
       double power = Math.pow(numFive, numSix);
       
       //set the labels (answers) by changing the double answers to string then displaying
 //the result of the method's calculations, that were set to variables.
       lblNumPower.setText(Double.toString(power));
    }
    private void btnHypotenuseActionPreformed(java.awt.event.ActionEvent awt) {
    //set the variables to the value in the text fields as integers.
        int numSeven = Integer.parseInt(txtNumSeven.getText());
        int numEight = Integer.parseInt(txtNumEight.getText());
        
    //set the variables to the value that the method calculates.
        double hypotenuse = Math.hypot(numSeven, numEight);
    
    //set the labels (answers) by changing the double answers to string then displaying
    //the result of the method's calculations, that were set to variables.
        lblNumHypotenuse.setText(Double.toString(hypotenuse));
    }
    
    private void btnRoundUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoundUpActionPerformed
    //set the variables to the value in the text fields as integers.
        int numNine = Integer.parseInt(txtNumNine.getText());
        
    //set the variables to the value that the method calculates
        double rounded = Math.ceil(numNine);
        
    //set the labels (answers) by changing the double answers to string then displaying
    //the result of the method's calculations, that were set to variables.
       lblNumRounded.setText(Double.toString(rounded));
    }//GEN-LAST:event_btnRoundUpActionPerformed
    
    private void btnSquareRootActionPreformed(java.awt.event.ActionEvent awt) {
    //set the variables to the value in the text fields as integers.
        int numTen = Integer.parseInt(txtNumTen.getText());
        
    //set the variables to the value that the method calculates
        double squared = Math.sqrt(numTen);
        
    //set the labels (answers) by changing the double answers to string then displaying
    //the result of the method's calculations, that were set to variables.
        lblNumSquared.setText(Double.toString(squared));
    }
    
    private void btnRadiansActionPreformed(java.awt.event.ActionEvent awt) {
    //set the variables to the value in the text fields as integers.
       int numEleven = Integer.parseInt(txtNumEleven.getText());
        
    //set the variables to the value that the method calculates
        double radians = Math.toRadians(numEleven);
    //set the labels (answers) by changing the double answers to string then displaying
    //the result of the method's calculations, that were set to variables.
        lblNumRadians.setText(Double.toString(radians));
    }
    
    private void txtNumOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumOneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagicMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagicMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagicMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagicMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagicMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBiggest;
    private javax.swing.JButton btnHypotenuse;
    private javax.swing.JButton btnPower;
    private javax.swing.JButton btnRadians;
    private javax.swing.JButton btnRoundUp;
    private javax.swing.JButton btnSmallest;
    private javax.swing.JButton btnSquareRoot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblNumBiggest;
    private javax.swing.JLabel lblNumHypotenuse;
    private javax.swing.JLabel lblNumPower;
    private javax.swing.JLabel lblNumRadians;
    private javax.swing.JLabel lblNumRounded;
    private javax.swing.JLabel lblNumSmallest;
    private javax.swing.JLabel lblNumSquared;
    private javax.swing.JTextField txtNumEight;
    private javax.swing.JTextField txtNumEleven;
    private javax.swing.JTextField txtNumFive;
    private javax.swing.JTextField txtNumFour;
    private javax.swing.JTextField txtNumNine;
    private javax.swing.JTextField txtNumOne;
    private javax.swing.JTextField txtNumSeven;
    private javax.swing.JTextField txtNumSix;
    private javax.swing.JTextField txtNumTen;
    private javax.swing.JTextField txtNumThree;
    private javax.swing.JTextField txtNumTwo;
    // End of variables declaration//GEN-END:variables
}
