/*
Riley Denoon
SuperString
April 17th 2020
 */
package SuperString;

/**
 *
 * @author melanie
 */
public class SuperStringFrame extends javax.swing.JPanel {

    /**
     * Creates new form SuperStringFrame
     */
    public SuperStringFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        txtValueEnteredLength = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnLength = new javax.swing.JButton();
        lblLength = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEnteredLowercase = new javax.swing.JTextField();
        btnToUppercase = new javax.swing.JButton();
        lblUppercase = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEnteredFourth = new javax.swing.JTextField();
        btnFourthSpot = new javax.swing.JButton();
        lblFourthSpot = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFirstNumberEntered = new javax.swing.JTextField();
        txtSecondNumberEntered = new javax.swing.JTextField();
        btnIdentical = new javax.swing.JButton();
        lblIdentical = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtString = new javax.swing.JTextField();
        txtLetter = new javax.swing.JTextField();
        btnLetterFound = new javax.swing.JButton();
        lblLetterFound = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtStringEntered = new javax.swing.JTextField();
        btnFourToSix = new javax.swing.JButton();
        lblFourToSix = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtStringWithA = new javax.swing.JTextField();
        btnAToX = new javax.swing.JButton();
        lblAToX = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        txtValueEnteredLength.setText("Type here");
        txtValueEnteredLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValueEnteredLengthActionPerformed(evt);
            }
        });

        jLabel1.setText("Super String Software");

        btnLength.setText("Find Length");
        btnLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLengthActionPerformed(evt);
            }
        });

        lblLength.setText(".........");

        jLabel2.setText("Enter a string, the program will output the number of characters in the string.");

        jLabel3.setText("Enter a string in lowercase, the program will output the characters in all capital letters. ");

        txtEnteredLowercase.setText("Type here");
        txtEnteredLowercase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnteredLowercaseActionPerformed(evt);
            }
        });

        btnToUppercase.setText("ALL CAPS");
        btnToUppercase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToUppercaseActionPerformed(evt);
            }
        });

        lblUppercase.setText("........");

        jLabel4.setText("Enter a string, the program will output the character at the 4th spot. ");

        txtEnteredFourth.setText("Type Here");

        btnFourthSpot.setText("Fourth Spot ");
        btnFourthSpot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourthSpotActionPerformed(evt);
            }
        });

        lblFourthSpot.setText(".........");

        jLabel5.setText("Enter two strings, the program will output whether or not they are identical.");

        txtFirstNumberEntered.setText("Type Here");

        txtSecondNumberEntered.setText("Type Here");

        btnIdentical.setText("Identical?");
        btnIdentical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdenticalActionPerformed(evt);
            }
        });

        lblIdentical.setText("..........");

        jLabel6.setText("Enter a string and a letter, the program will output if the letter is in the string. ");

        txtString.setText("String Here");

        txtLetter.setText("Letter Here");

        btnLetterFound.setText("Letter Found?");
        btnLetterFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLetterFoundActionPerformed(evt);
            }
        });

        lblLetterFound.setText("..........");

        jLabel7.setText("Enter a String that is at least 8 characters long. The program will output characters 4 to 6.");

        txtStringEntered.setText("String Here");

        btnFourToSix.setText("Char 4 to 6");
        btnFourToSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourToSixActionPerformed(evt);
            }
        });

        lblFourToSix.setText(".........");

        jLabel8.setText("Enter a string that contains at least one \"a\", the program will replace all of the \"a'''s ");

        txtStringWithA.setText("String Here");

        btnAToX.setText("Replace \"a\"");
        btnAToX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAToXActionPerformed(evt);
            }
        });

        lblAToX.setText(".........");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLetter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLetterFound))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtStringEntered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addComponent(btnFourToSix)))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtValueEnteredLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnLength)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLength)
                                .addGap(63, 63, 63))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtEnteredLowercase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(btnToUppercase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUppercase)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEnteredFourth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(btnFourthSpot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFourthSpot)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFirstNumberEntered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSecondNumberEntered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnIdentical)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblIdentical))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFourToSix)
                                    .addComponent(lblLetterFound))))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtStringWithA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(btnAToX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAToX)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLength)
                    .addComponent(txtValueEnteredLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLength))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnteredLowercase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToUppercase)
                    .addComponent(lblUppercase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnteredFourth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFourthSpot)
                    .addComponent(lblFourthSpot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstNumberEntered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSecondNumberEntered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIdentical)
                    .addComponent(lblIdentical))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLetter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLetterFound)
                    .addComponent(lblLetterFound))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStringEntered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFourToSix)
                    .addComponent(lblFourToSix))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStringWithA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAToX)
                    .addComponent(lblAToX))
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtValueEnteredLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValueEnteredLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValueEnteredLengthActionPerformed

    private void btnLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLengthActionPerformed
        //Declare variables
        String valueEnteredLength;
       int length;
       //Use the getText(); function to retrieve the word the user inputs
       valueEnteredLength = txtValueEnteredLength.getText();
       //Use the method of length(); to find the length of the word the user enters into the text interface
       length = valueEnteredLength.length();
       //Display the length of the word into lblLength, and use the string value of 'length'
        lblLength.setText(String.valueOf(length));
        
    }//GEN-LAST:event_btnLengthActionPerformed

    private void btnToUppercaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToUppercaseActionPerformed
        //Declare variables 
        String enteredLowercase;
        String uppercase;
        //use the getText(); function to retrieve the word the user inputs
        enteredLowercase = txtEnteredLowercase.getText();
        //Use the method toUpperCase(); to change the word into all upercase letters. 
        uppercase = enteredLowercase.toUpperCase();
        //Display the length of the word into lblUppercase
        lblUppercase.setText(uppercase);
    }//GEN-LAST:event_btnToUppercaseActionPerformed

    private void txtEnteredLowercaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnteredLowercaseActionPerformed
       
    }//GEN-LAST:event_txtEnteredLowercaseActionPerformed

    private void btnFourthSpotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourthSpotActionPerformed
         //Declare Variables 
        String enteredValueFourth;
        int fourthSpot;
        //Use the getText(); function to use the word the user inputs. 
        enteredValueFourth = txtEnteredFourth.getText();
        //Use the method charAt(); to find the character at the fourth spot.
        fourthSpot = enteredValueFourth.charAt(4);
        //Display the fourth character as a string value into lblfourthSpot
        lblFourthSpot.setText(String.valueOf(fourthSpot));
    }//GEN-LAST:event_btnFourthSpotActionPerformed

    private void btnIdenticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdenticalActionPerformed
        //Declare Variables
        String firstNumber;
        String secondNumber;
        String identical;
        //Use the getText(); function to retrieve the words the users input.
        firstNumber = txtFirstNumberEntered.getText();
        secondNumber = txtSecondNumberEntered.getText();
        //use an if statement to determine if both strings are identical using equals
        
        if (firstNumber.equals(secondNumber)) {
            identical = "These are identical";
        }
        else {
            identical = "These aren't identical";
        }
        //Display if the two string are equal by setting lblIdentical to what the answer is given from the if statement. 
        lblIdentical.setText(identical);
    }//GEN-LAST:event_btnIdenticalActionPerformed

    private void btnLetterFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLetterFoundActionPerformed
        //Declare variables
        String wordEntered;
        String letterEntered;
        String inWord;
        //Use the getText(); function to retrieve the word and letter form the text box.
        wordEntered = txtString.getText();
        letterEntered = txtLetter.getText();
        //Use an if statement to display if the letter is in the word
        if (wordEntered.contains(letterEntered)) {
            //if the letter is in the word then inWord changes to 'The letter is in the word'
            inWord = "The letter is in the word";
            //Set lblLetterFound to display inWord
            lblLetterFound.setText(String.valueOf(inWord));
        }
        else 
        {
            inWord = "The letter is not in the word";
            lblLetterFound.setText(String.valueOf(inWord));
        }
        //Use the contains(); method to determine if the letter is in the word, set as a string value
        //inWord = String.valueOf(wordEntered.contains(letterEntered));
        //Display the letter contained 
        //lblLetterFound.setText(String.valueOf(inWord));
    }//GEN-LAST:event_btnLetterFoundActionPerformed

    private void btnFourToSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourToSixActionPerformed
        //Declare variables
        String wordInput;
        String four;
        String five;
        String six;
       int num4 = 3;
       int num5 = 4;
       int num6 = 5;
        //Use the getText(); function to get the word.
        wordInput = txtStringEntered.getText();
        //Use the method charAt(); to get the characters at that point. 
        four = String.valueOf(wordInput.charAt(num4));
        five = String.valueOf(wordInput.charAt(num5));
        six = String.valueOf(wordInput.charAt(num6));
        //set the label to the letters at position 4,5,6.
        lblFourToSix.setText(four+five+six);
    }//GEN-LAST:event_btnFourToSixActionPerformed

    private void btnAToXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAToXActionPerformed
        //Decleare variables
        String wordEntered; 
        //Use the getText(); function to get the word.
        wordEntered = txtStringWithA.getText();
        //Using the replace(); method replace all the a's with x's. 
        wordEntered = wordEntered.replace("a","x");
        //Set the label to the modified word. 
        lblAToX.setText(wordEntered);
    }//GEN-LAST:event_btnAToXActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAToX;
    private javax.swing.JButton btnFourToSix;
    private javax.swing.JButton btnFourthSpot;
    private javax.swing.JButton btnIdentical;
    private javax.swing.JButton btnLength;
    private javax.swing.JButton btnLetterFound;
    private javax.swing.JButton btnToUppercase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAToX;
    private javax.swing.JLabel lblFourToSix;
    private javax.swing.JLabel lblFourthSpot;
    private javax.swing.JLabel lblIdentical;
    private javax.swing.JLabel lblLength;
    private javax.swing.JLabel lblLetterFound;
    private javax.swing.JLabel lblUppercase;
    private javax.swing.JTextField txtEnteredFourth;
    private javax.swing.JTextField txtEnteredLowercase;
    private javax.swing.JTextField txtFirstNumberEntered;
    private javax.swing.JTextField txtLetter;
    private javax.swing.JTextField txtSecondNumberEntered;
    private javax.swing.JTextField txtString;
    private javax.swing.JTextField txtStringEntered;
    private javax.swing.JTextField txtStringWithA;
    private javax.swing.JTextField txtValueEnteredLength;
    // End of variables declaration//GEN-END:variables
}
